ancestor: null
releases:
  0.1.0:
    changes:
      major_changes:
      - Adds Configuration as Code filetree_create - A role to export and convert
        all  Controller's objects configuration in yaml files to be consumed with
        previous roles.
      - Adds Configuration as Code filetree_read role - A role to load controller
        variables (objects) from a hierarchical and scalable directory structure.
      - Adds Configuration as Code object_diff role - A role to get differences between
        code and controller. It will give us the lists to remove absent objects in
        the controller which they are not in code.
      minor_changes:
      - Adds credential and organization options for schedule role.
      - inventory_sources - update ``source_vars`` to parse Jinja variables using
        the same workaround as inventories role.
    fragments:
    - casc_roles.yml
    - inventory_sources.yml
    - schedule_role.yml
    release_date: '2022-08-30'
  1.0.0:
    changes:
      bugfixes:
      - Add input_inventories to the output of Constructed Inventories.
      - Add instance_groups to the output of Constructed Inventories.
      - Fixes issue where the input tags were not accepted or being skipped
      - filetree_create - Corrected th4e following vars; controller_hostname, controller_oauthtoken,
        and controller_validate_certs
      - filetree_create export inventories source vars with proper indention
      - filetree_create export missing inventory ask settings of workflows
      - filetree_create export missing inventory for workflow node
      - filetree_create export missing limit of workflow nodes
      - filetree_create export missing limits settings of workflows
      - filetree_create export missing verbosity for node
      - filetree_create export verbosity for node when ask_verbosity_on_launch is
        defined
      - filetree_create exported properly smart inventories host filter (double quotes
        issue)
      - filetree_create extra_vars regex issue
      - filetree_create fix wrong object type name in user roles template
      - filetree_create is able to export empty extra vars of JT and WF
      - filetree_create job_template and workflow_job_template issues with complex
        fields
      - filetree_create job_template and workflow_job_template survey default values
        issue when they are multiline
      - filetree_create job_template and workflow_job_template survey issue when the
        survey_spec was empty (but defined)
      - filetree_create job_template and workflow_job_template survey was failing
        when it was empty
      - filetree_create job_template double quote issue
      - filetree_create missing single quotes for hostfilter in smart inventories
      - filetree_create no longer export schedules extra data when extra_vars of job
        template is empty (null issue)
      - filetree_create properly escape every variable with unsafe
      - filetree_create remove state from workflow job templates output to avoid problems
        when importing those files
      - filetree_create roles export issue
      - filetree_create roles export issues introduced by PR
      - filetree_create use proper global template variable name
      - fix empty and malformed file for credential_types
      major_changes:
      - filetree_create is able to use external dictionary to modify object during
        the export
      minor_changes:
      - Add credential_input_sources to the filetree create
      - Constructed inventories now produce an inventory source which can be used
        to control items such as limit and source_vars for the constructed inventory
      - filetree_create able to export single inventory
      - filetree_create is able to export approval node of workflow
      - filetree_create is able to export inventory without sources/hosts/groups.
      - filetree_create is able to export variables without key sorting
      - filetree_create projects bool variables are stored without quotes
      - filetree_create should not export hosts of smart/constructed inventories as
        they are based on existing inventories
      - filetree_create should use plural inventories word instead of singular inventory
    fragments:
    - constructed_inventories.yml
    - filetree_create_24.yml
    - filetree_create_allow_skip_inventory_related_objects.yml
    - filetree_create_credential_input_sources.yml
    - filetree_create_customize_exported_objects.yml
    - filetree_create_disabling_key_sorting.yml
    - filetree_create_double_quotes_issue.yaml
    - filetree_create_empty_credential_types.yml
    - filetree_create_extra_vars_issue.yml
    - filetree_create_hostfilter_issue.yml
    - filetree_create_hostfilter_missing_quotes.yaml
    - filetree_create_input_tags.yml
    - filetree_create_inventories_source_vars_idention.yml
    - filetree_create_inventory_template_variable_typo.yaml
    - filetree_create_inventory_unification.yml
    - filetree_create_issue39.yaml
    - filetree_create_missing_extra_vars.yml
    - filetree_create_missing_inventory_ask.yml
    - filetree_create_missing_limit_WF_nodes.yml
    - filetree_create_missing_limits_workflows.yml
    - filetree_create_missing_support_approval_node.yml
    - filetree_create_node_verbosity_added_when_not_needed.yaml
    - filetree_create_node_verbosity_issue.yml
    - filetree_create_projects_bool_variables.yml
    - filetree_create_role_issue.yml
    - filetree_create_role_issues.yaml
    - filetree_create_schedule_extra_data_issue.yml
    - filetree_create_single_inventory.yaml
    - filetree_create_smart_constructed_inventory_hosts_export.yml
    - filetree_create_survey_defaults_issue.yaml
    - filetree_create_survey_issue.yaml
    - filetree_create_surveys_issue.yaml
    - filetree_create_unsafe_regex_issue.yml
    - filetree_create_user_roles_fix_workflow_name.yml
    - filetree_create_workflow_job_templates.yaml
    - readme_req.yml
    release_date: '2025-04-17'
  1.1.0:
    changes:
      bugfixes:
      - "BREAKING - filetree_read default var updated to align with new aap_users
        \u2014 may break old user definitions if they're using default path for users
        definition."
      - Fix the organization ID variable used to look for the organization name of
        the current decision environment
      - Fix the wrong variable path used at inventory_sources to access the source_project
        field
      - Set the lookup plugin in filetree_create to use the ansible.platform.gateway_api
        plugin to capture the AAP version
      - filetree_create no longer has issue with backslashes in survey and extra vars
      - filetree_create no longer has issue with strings like 123-123-123 in survey
        and extra vars
      - fix a truthy value at the survey for the workflow job templates. Set it to
        lowercase.
      minor_changes:
      - Add a filter to allow exporting the Job Templates based on an assigned label
      - Updated linting rules to mock infra.aap_configuration collection
    fragments:
    - allow_export_jt_by_label.yml
    - filetree_create_api_plugin.yml
    - filetree_create_eda_rulebook_activations.yaml
    - filetree_create_inventories_source_bugfix.yml
    - filetree_create_survey_extra_vars_issues.yml
    - filetree_create_workflow_job_templates.yml
    - filetree_read_default_user_path.yml
    - lint.yml
    release_date: '2025-06-06'
  1.1.1:
    changes:
      bugfixes:
      - object_diff adapt object diff api calls to fit with AAP 2.5 api changes. It
        means to use api/controller or api/gateway for each particular case.
    fragments:
    - object_diff_fix_api_endpoints.yml
    release_date: '2025-06-15'
  2.0.0:
    changes:
      breaking_changes:
      - Remove aap<=2.4 api endpoints and version detections in the filetree_create
        role
      bugfixes:
      - Change connection variables to AAP from 'controller_*' to 'aap_*' when exporting
        the 'inventory_sources'.
      - Fix the exported contents of survey's choices in workflow job templates to
        avoid to have the clause '!unsafe' inside the generated string.
      - Set the correct API URL for the controller applications endpoint
      - There was a format error in the output after each key occurence. The template
        has been fixed.
      - There was an indentation error in the output at the `inputs` and `injectors`
        sections. The template has been fixed.
      - There was an indentation error in the output at the `inputs` and `injectors`
        sections. The template has been fixed.
      major_changes:
      - New role to update Configuration as Code files from 2.4 (infra.controller_configuration)
        format to 2.5 (infra.aap_configuration_extended)
      - Remove controller_api_plugin and eda_api_plugin variables in favour of ansible.platform.gateway_api
      minor_changes:
      - Let the sensitive data of the credentials and users to be defined externally
        through a well know variables
      - Use correct API endpoint when connecting to AAP 2.5 when determining super
        user privileges
    fragments:
    - 137-fix-use_correct_api_endpoint_superuser
    - filetree_create_controller_applications.yaml
    - filetree_create_controller_credential_types.yaml
    - filetree_create_controller_inventories.yaml
    - filetree_create_controller_workflow_job_templates.yaml
    - filetree_create_eda_credential_types.yaml
    - filetree_create_externalize_credentials.yml
    - filetree_create_gateway_service_keys.yaml
    - filetree_create_issue136.yaml
    - new_role_upgrade_config.yml
    - update_collections.yaml
    release_date: '2025-09-01'
  3.0.0:
    changes:
      bugfixes:
      - Fixes a bug where a survey option's default choice wasn't included in the
        choice list
      - Fixes an issue with the filetree_create role adding a '...' separate between
        each item in the job templates list flatten output is set to true.
      major_changes:
      - Remove controller_api_plugin and controller_role_plugin variables in favour
        of ansible.platform.gateway_api and infra.aap_configuration_extended.controller_object_diff
      minor_changes:
      - Export PAH objects.
      - Fix the markdown errors for the CI to work properly
    fragments:
    - 152-fix_filetree_create_survey_option_handling.yml
    - 153-fix_adding_divider_between_job_templates_list.yml
    - filetree_create_issue130.yaml
    - mdissues.yaml
    - object_diff_update_collections.yaml
    release_date: '2025-09-23'
  3.0.1:
    changes:
      bugfixes:
      - Fix the issues detected in the last import log (galaxy)
    fragments:
    - import_log_issues.yaml
    release_date: '2025-09-25'
  3.0.2:
    changes:
      bugfixes:
      - Fix default value for webhook_service in workflow job templates
      - Fix verbosity key in workflow job templates
      - Upgraded offline_sync to work with AAP 2.5+
      - upgrade_config fix the names of the variables in the generated files
    fragments:
    - upgrade_config.yaml
    - upgrade_offline_sync.yml
    - workflow_job_templates_template.yml
    release_date: '2025-10-15'
