download_url: https://console.redhat.com/api/automation-hub/v3/plugin/ansible/content/published/collections/artifacts/ansible-platform-2.6.20250924.tar.gz
format_version: 1.0.0
name: platform
namespace: ansible
server: https://console.redhat.com/api/automation-hub/content/published/
signatures:
- pubkey_fingerprint: 39B5D759361A97464C564A8FE1A4BD708A828AAD
  pulp_created: '2025-09-17T20:59:47.014436Z'
  signature: '-----BEGIN PGP SIGNATURE-----


    iQIcBAABCAAGBQJoyyEWAAoJEOGkvXCKgoqt5OwP/RXZu/+TFRsqcy1fcHjxdZXO

    QhMQs4zJIs/F0r9AWNWOZyZAf8bV1zVaeety+NX17uZZ3fEytEnqxPj9aGzks3c+

    HPqLk7vfRNlC8CGLyuCM5sJ263cOVDhW57tjb63NuTN4kHDEzIPQl0qQa/qn4/+q

    sOuCu7hE9hQRPro5qo/57pfz6WKukFiSf+KpZI792NGpe25dtBg7FHKUZEc4tBba

    gMngUF0H2FH85Gy+cf5HH+G6+Xal82PL+UIO55RQ9SRuaauN54RKIhCwjE6vXNjk

    ZZnu5eNeTU3mrBGrMsQNGHpyIQ4FNTWFydMLKJ9k218uJnMbz9GYp0ECY0ouNbqB

    VMnFJGWy8xL28marzF94umJw7XZn3kPi79NjPYMaIfsPNbRr6pGob+oUSdJ6g853

    7L3OgRFwoaRWhpJPTrKknFeUednPCxjBe7S0UI//fd6iBJSP6OlPBQl3s4aTP8Wv

    hGXVe5MvHZaSv68FVhKARf03tH878W9rQDwjaif8VtycZHe9JYTfmLOv2cKVnELV

    crB6FoG9RwLQYDi48qVnv8QHp0vdGgMDGATQg/dQtLDXVaERnibNCuRzwtYrsh75

    +Z/3k9VOmuISqoc7kQUunxrgpJOFyXLE8IzddpvxTxpPxfDd0A1qs8rQxqJj6RTY

    yO+4HEfAVYgegH2q/HAi

    =vrGx

    -----END PGP SIGNATURE-----

    '
  signing_service: null
version: 2.6.20250924
version_url: /api/automation-hub/content/published/v3/plugin/ansible/content/published/collections/index/ansible/platform/versions/2.6.20250924/
