download_url: https://console.redhat.com/api/automation-hub/v3/plugin/ansible/content/published/collections/artifacts/ansible-controller-4.7.4.tar.gz
format_version: 1.0.0
name: controller
namespace: ansible
server: https://console.redhat.com/api/automation-hub/content/published/
signatures:
- pubkey_fingerprint: 39B5D759361A97464C564A8FE1A4BD708A828AAD
  pulp_created: '2025-10-23T07:47:12.154975Z'
  signature: '-----BEGIN PGP SIGNATURE-----


    iQIcBAABCAAGBQJo+d10AAoJEOGkvXCKgoqto+sP/i2t1M2IrNp2VJqpTzdzv2ow

    GNWD37OG+XsOCYlxUpRNeyVVJuJMnNvSHBVpxL9r8aRdjMzLy9qvw6o8C/NnjWls

    I8/TD4hXTl/NaTZhrGDBdfNjYs4UOxYbnqY3I7DDWL8tNZnRiMOBkItld6tC7d1P

    /JaY2hF1QHp2zOoqOECUSKYCHNSD12/djF8TXfOW0P54P37a9P78wjMfBdc+WUW5

    htzERKYETnsFR4oUbUEZOIorJ6ImpS67yiMtRK40EqSc65hQZ5u3O0aOgiHd8D4A

    Z3ycqHhJ7WNLQECwqfm4WhkwhUUEVP93CLsV0UvIbTP13v4o3ot/7i59emHccCAe

    eAdw92H6y6fgmX/xy+d8vB2ASQHO8yaayRGJAALRC3U2iYQEqWaZgUoX88KI+fyw

    SLpYNYxadfj0N+Sbt3NWrWk/quYYuk6Sp0g6385xLQS6dsnQCFvymXyidH0TGXNS

    /BDKIRrvvDEKpYSDEYz0vaaI9xnYg7qVvuZd8Jcz+hv1Q0uWlyPWN9+cm3lgG3jJ

    6OaDEox9kVw/Xiyn6kAvPKdd903i3ebcHDl7GDGNDJxlxQVSxyUKRqQwTP8dMN86

    IQxgZYTJD2oCx7gIC1Q1jwuYH7EESPs3wDV5rAfpJ9zJZIw8qnzMO3rNTIeQZZU7

    7yLs7/YTqU2IwCPvZMe4

    =Ux78

    -----END PGP SIGNATURE-----

    '
  signing_service: null
version: 4.7.4
version_url: /api/automation-hub/content/published/v3/plugin/ansible/content/published/collections/index/ansible/controller/versions/4.7.4/
