download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/infra-aap_configuration_extended-3.0.2.tar.gz
format_version: 1.0.0
name: aap_configuration_extended
namespace: infra
server: https://galaxy.ansible.com/api/
signatures: []
version: 3.0.2
version_url: /api/v3/plugin/ansible/content/published/collections/index/infra/aap_configuration_extended/versions/3.0.2/
